-- Stripe orders + intake forms (Websit-SAAS)

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  stripe_session_id text not null unique,
  stripe_customer_id text,
  email text,
  name text,
  package text not null,
  amount integer not null,
  currency text not null default 'sek',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.intake_forms (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  company text,
  phone text,
  goal text,
  inspiration text,
  notes text,
  answers_json jsonb,
  meeting_link text,
  booking_start timestamptz,
  booking_end timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.busy_blocks (
  id bigint generated by default as identity primary key,
  start_time timestamptz not null,
  end_time timestamptz not null,
  reason text,
  created_at timestamptz not null default now(),
  constraint busy_blocks_time_order check (end_time > start_time)
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  start_time timestamptz not null,
  end_time timestamptz not null,
  created_at timestamptz not null default now(),
  constraint bookings_time_order check (end_time > start_time)
);

alter table public.orders enable row level security;
alter table public.intake_forms enable row level security;
alter table public.busy_blocks enable row level security;
alter table public.bookings enable row level security;

-- Helper: booked/blocked intervals for a given local date (Europe/Stockholm)
create or replace function public.booked_slots_for_date(day date)
returns table(start_time timestamptz, end_time timestamptz, kind text)
language sql
stable
as $$
  select b.start_time, b.end_time, 'booking'::text
  from public.bookings b
  where (b.start_time at time zone 'Europe/Stockholm')::date = day

  union all

  select bb.start_time, bb.end_time, 'blocked'::text
  from public.busy_blocks bb
  where (bb.start_time at time zone 'Europe/Stockholm')::date = day;
$$;

-- Helper: check for overlap against existing bookings/blocks
create or replace function public.is_slot_available(start_time timestamptz, end_time timestamptz)
returns boolean
language sql
stable
as $$
  select
    not exists (
      select 1 from public.bookings b
      where tstzrange(b.start_time, b.end_time, '[)') && tstzrange(start_time, end_time, '[)')
    )
    and not exists (
      select 1 from public.busy_blocks bb
      where tstzrange(bb.start_time, bb.end_time, '[)') && tstzrange(start_time, end_time, '[)')
    );
$$;

-- No public policies by default. Edge Functions use service_role and bypass RLS.
