-- Stripe orders + intake forms (Websit-SAAS)

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  stripe_session_id text not null unique,
  stripe_customer_id text,
  email text,
  name text,
  package text not null,
  amount integer not null,
  currency text not null default 'sek',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.intake_forms (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  company text,
  phone text,
  goal text,
  inspiration text,
  notes text,
  answers_json jsonb,
  meeting_link text,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
alter table public.intake_forms enable row level security;

-- No public policies by default. Edge Functions use service_role and bypass RLS.
